name: MLflow to DagsHub CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-latest
    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}  # Pastikan secret ini ada di GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Pastikan ada file requirements.txt
        pip install dagshub

    - name: Verify data path
      run: |
        echo "Current dir: $(pwd)"
        ls -R MLProject/  # Pastikan file CSV ada di folder MLProject

    - name: Run Experiment
      run: python MLProject/modelling.py

    - name: Check MLflow logs
      if: always()
      run: |
        echo "MLflow runs:"
        ls -l /tmp/mlruns || echo "No local MLflow data"
