name: ML Pipeline

on: [push, workflow_dispatch]

jobs:
  run-experiment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install packages
      run: |
        pip install --upgrade pip
        pip install dagshub==0.3.5  # Versi spesifik yang stabil
        pip install mlflow==2.3.2 scikit-learn pandas numpy joblib
        pip install "dagshub>=0.3.4,<0.4.0"  # Double insurance

    - name: Verify imports
      run: |
        python -c "
        try:
            from dagshub import dagshub
            print('✅ DagsHub import sukses!')
        except ImportError as e:
            print(f'❌ Gagal import: {e}')
            raise
        "

    - name: Run experiment
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python MLProject/modelling.py
