name: ML Pipeline with DagsHub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-latest
    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}  # Make sure this secret exists
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dagshub==0.3.4 mlflow==2.3.1
        pip install pandas scikit-learn numpy joblib
    
    - name: Verify data path
      run: |
        echo "Current directory:"
        pwd
        ls -la
        echo "MLProject contents:"
        ls -la MLProject/
    
    - name: Run ML experiment
      run: python MLProject/modelling.py
